2024-08-28 13:43:19,721 - CAPIFProviderConnector - ERROR - File not found: /Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json
2024-08-28 13:43:19,723 - CAPIFProviderConnector - ERROR - Unexpected error: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-28 13:43:19,723 - CAPIFProviderConnector - ERROR - Failed to offboard and deregister Provider: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-29 10:59:17,100 - ServiceDiscoverer - WARNING - Received 404 error, redirecting to register security service
2024-08-29 11:23:59,930 - CAPIFProviderConnector - ERROR - File not found: /Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json
2024-08-29 11:23:59,932 - CAPIFProviderConnector - ERROR - Unexpected error: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-29 11:23:59,933 - CAPIFProviderConnector - ERROR - Failed to offboard and deregister Provider: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-29 11:57:38,003 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: string indices must be integers, not 'str'
2024-08-29 11:58:38,607 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 403 Client Error: FORBIDDEN for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis
2024-08-29 11:59:02,593 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/02eff6e1b3a8f7c8044a92ee8a30bd
2024-08-29 12:00:46,600 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: string indices must be integers, not 'str'
2024-08-29 12:02:21,683 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: string indices must be integers, not 'str'
2024-08-29 12:03:44,302 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: string indices must be integers, not 'str'
2024-08-29 12:05:00,505 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF_/nef/api/v1/3gpp-monitor-event-13/'
2024-08-29 12:06:33,897 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF_/nef/api/v1/3gpp-monitor-event-13/'
2024-08-29 12:09:50,094 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF_/nef/api/v1/3gpp-monitor-event-13/.json'
2024-08-29 12:16:38,692 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF_/nef/api/v1/3gpp-monitor-event-13/.json'
2024-08-29 12:18:25,895 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF-/nef/api/v1/3gpp-monitor-event-13/-api.json'
2024-08-29 12:20:05,794 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/CAPIF-/nef/api/v1/3gpp-monitor-event-13/-api.json'
2024-08-29 12:26:46,697 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/581e24c349591e5a09a2085028f976
2024-08-29 12:27:11,409 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: 'str' object has no attribute 'get'
2024-08-29 13:01:15,878 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/6f8bddfe671a9c1b56bf8c753e9223
2024-08-29 13:05:01,007 - CAPIFProviderConnector - ERROR - Unexpected error during service unpublication: '_io.TextIOWrapper' object is not subscriptable
2024-08-29 13:08:36,224 - CAPIFProviderConnector - ERROR - Unexpected error during service unpublication: I/O operation on closed file.
2024-08-29 13:11:18,040 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/9fe917a30d5279a5cbbba6b844c2ca
2024-08-29 13:11:41,319 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/de766971736ca69b578642f9942447
2024-08-29 13:32:35,020 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: 'str' object has no attribute 'get'
2024-08-29 13:34:47,420 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: 'str' object has no attribute 'get'
2024-08-29 13:36:57,123 - CAPIFProviderConnector - ERROR - Unexpected error during service publication: write() argument must be str, not dict
2024-08-29 14:09:56,938 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 401 Client Error: UNAUTHORIZED for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APFe9b968ba70670ee9ac5d37eeca58dd/service-apis/0372d034b7a200f24c81d23e4fec05
2024-08-30 11:32:21,190 - ServiceDiscoverer - WARNING - Received 404 error, redirecting to register security service
2024-08-30 11:36:47,921 - CAPIFProviderConnector - ERROR - Request to CAPIF failed: 404 Client Error: NOT FOUND for url: https://capif-prev.mobilesandbox.cloud:36212/published-apis/v1/APF39d212eeb636f3d93a046786a71438/service-apis/
2024-08-30 12:47:16,866 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers
2024-08-30 12:47:16,867 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers
2024-08-30 12:54:08,419 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_invoker_certificate_folder/echeva_0capif_api_security_context_details-echeva_0.json'
2024-08-30 12:54:08,420 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_invoker_certificate_folder/echeva_0capif_api_security_context_details-echeva_0.json'
2024-08-30 12:54:37,511 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: '_io.TextIOWrapper' object is not subscriptable
2024-08-30 12:54:37,511 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: '_io.TextIOWrapper' object is not subscriptable
2024-08-30 12:55:16,710 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: the JSON object must be str, bytes or bytearray, not TextIOWrapper
2024-08-30 12:55:16,710 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: the JSON object must be str, bytes or bytearray, not TextIOWrapper
2024-08-30 12:56:21,217 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: the JSON object must be str, bytes or bytearray, not TextIOWrapper
2024-08-30 12:56:21,218 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: the JSON object must be str, bytes or bytearray, not TextIOWrapper
2024-08-30 12:57:19,711 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: string indices must be integers, not 'str'
2024-08-30 12:57:19,718 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: string indices must be integers, not 'str'
2024-08-30 12:59:20,996 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 12:59:20,997 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:05:57,357 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 405 Client Error: METHOD NOT ALLOWED for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:05:57,359 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 405 Client Error: METHOD NOT ALLOWED for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:06:43,574 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:06:43,575 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:07:23,472 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:07:23,472 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0
2024-08-30 13:08:12,638 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0 (Caused by SSLError(SSLError(116, '[X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3916)')))
2024-08-30 13:08:12,638 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding and deregistering: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0 (Caused by SSLError(SSLError(116, '[X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3916)')))
2024-08-30 13:08:29,332 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0 (Caused by SSLError(SSLError(116, '[X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3916)')))
2024-08-30 13:08:29,332 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding and deregistering: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV788093355599a49339270b0a76eba0 (Caused by SSLError(SSLError(116, '[X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:3916)')))
2024-08-30 13:26:34,571 - CAPIFProviderConnector - ERROR - File not found: /Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json
2024-08-30 13:26:34,571 - CAPIFProviderConnector - ERROR - Unexpected error: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-30 13:26:34,571 - CAPIFProviderConnector - ERROR - Failed to offboard and deregister Provider: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_provider_certificate_folder/echeva_0/capif_provider_details.json'
2024-08-30 13:43:45,150 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: [Errno 2] No such file or directory: '/Users/IDB0128/Documents/OpenCapif/test_invoker_certificate_folder/echeva_0cert_req.csr'
2024-08-30 13:44:36,850 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: decoding to str: need a bytes-like object, _io.TextIOWrapper found
2024-08-30 13:44:36,851 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: decoding to str: need a bytes-like object, _io.TextIOWrapper found
2024-08-30 13:45:44,256 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: decoding str is not supported
2024-08-30 13:45:44,256 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: decoding str is not supported
2024-08-30 13:46:10,845 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: Expecting value: line 1 column 1 (char 0)
2024-08-30 13:47:00,552 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: decoding str is not supported
2024-08-30 13:47:00,552 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: decoding str is not supported
2024-08-30 13:50:15,606 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV039c494f693c0bd654a939293c9d6a
2024-08-30 13:50:15,606 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV039c494f693c0bd654a939293c9d6a
2024-08-30 13:50:58,498 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV039c494f693c0bd654a939293c9d6a
2024-08-30 13:50:58,498 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV039c494f693c0bd654a939293c9d6a
2024-08-30 13:52:09,716 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc
2024-08-30 13:52:09,716 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 401 Client Error: Unauthorized for url: https://capif-prev.mobilesandbox.cloud:36212/api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc
2024-08-30 13:55:25,097 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: 'apiInvokerCertificate'
2024-08-30 13:55:25,099 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: 'apiInvokerCertificate'
2024-08-30 13:57:35,365 - CAPIFInvokerConnector - ERROR - Error during updating Invoker to CAPIF: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
2024-08-30 13:57:35,366 - CAPIFInvokerConnector - ERROR - Error during Invoker updating Invoker: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
2024-08-30 13:58:00,115 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
2024-08-30 13:58:00,115 - CAPIFInvokerConnector - ERROR - Error during Invoker offboarding and deregistering: HTTPSConnectionPool(host='capif-prev.mobilesandbox.cloud', port=36212): Max retries exceeded with url: /api-invoker-management/v1/onboardedInvokers/INV703891cb63cea360b8de9f0fc9f2fc (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)')))
